### Numpy Basics

In [1]:
import numpy as np

+ creat single & Multiple type array

+ Single Dimension Numpy

In [2]:
n1=np.array([1,2,45,7,5343])
n1

array([   1,    2,   45,    7, 5343])

In [3]:
type(n1)

numpy.ndarray

In [4]:
n2=np.array([[32,45,3,24,5],[34,5,6,734,6]])
n2

array([[ 32,  45,   3,  24,   5],
       [ 34,   5,   6, 734,   6]])

In [5]:
type(n2)

numpy.ndarray

In [6]:
n3=np.array([[23,45,2,45,3,4],[4,34,56,34,6,3]])
n3

array([[23, 45,  2, 45,  3,  4],
       [ 4, 34, 56, 34,  6,  3]])

In [7]:
n4=np.zeros((1,2))
n4

array([[0., 0.]])

In [8]:
n5=np.zeros((5,5))
n5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
n6=np.zeros((2,3))
n6

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
n7=np.zeros((6,6))
n7

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

+ creat 2 matrix full with 10

In [11]:
n8=np.full((2,2),(10))
n8
#(2,2) are dimensions while it filled with 10

array([[10, 10],
       [10, 10]])

In [12]:
n9=np.full((5,5),(5))
n9

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [13]:
n10=np.full((3,6),(9))
n10

array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

### Initializing Numpy array within a range

In [14]:
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
n2=np.arange(20,50,5)
n2

array([20, 25, 30, 35, 40, 45])

In [16]:
n3=np.arange(23,100)
n3

array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
       74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
       91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
n4=np.arange(23,100,20)
n4

array([23, 43, 63, 83])

### Initializing Numpy array with random Numbers

In [18]:
np1=np.random.randint(100,1000,10)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### Checking shape of Numpy arrays

In [19]:
n2=np.array([[2,3,4],[3,3,5]])
n2.shape

(2, 3)

In [20]:
n2.shape=(3,2)
n2

array([[2, 3],
       [4, 3],
       [3, 5]])

In [21]:
n4=np.array([[36,32,5],[2,31,5]])
n4.shape

(2, 3)

In [22]:
n4.shape = (3,2)
n4.shape

(3, 2)